# Generated by Django 5.2 on 2025-12-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def delete_existing_posts(apps, schema_editor):
    """Delete all existing posts before adding non-nullable author field."""
    Post = apps.get_model('posts', 'Post')
    Post.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, delete any existing posts
        migrations.RunPython(delete_existing_posts, migrations.RunPython.noop),
        # Then add the author field
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                to=settings.AUTH_USER_MODEL,
                default=1,  # Temporary default, won't be used as we deleted all posts
            ),
            preserve_default=False,
        ),
    ]
